apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: egesetz
data:
  V0_init.sql: |
    CREATE DATABASE IF NOT EXISTS eGesetz;
    CREATE DATABASE IF NOT EXISTS rbac;
    CREATE DATABASE IF NOT EXISTS editor;
    CREATE DATABASE IF NOT EXISTS files;
