apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-with-cockpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-with-cockpit
  template:
    metadata:
      labels:
        app: backend-with-cockpit
    spec:
      containers:
        - name: backend-with-cockpit
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: server.port
              value: {{ .Values.env.SERVER_PORT | quote }}

            - name: iam.url
              value: {{ .Values.env.IAM_URL | quote }}

            - name: backend.url.base
              value: {{ .Values.env.BACKEND_URL_BASE | quote }}
            - name: spa.url.base
              value: {{ .Values.env.SPA_URL_BASE | quote }}

            - name: spring.datasource.baseUrl
              value: {{ .Values.env.SPRING_DS_BASEURL | quote }}
            - name: spring.datasource.username
              value: {{ .Values.env.DB_USER | quote }}
            - name: spring.datasource.password
              value: {{ .Values.env.DB_PASS | quote }}

            - name: editor.url
              value: {{ .Values.env.EDITOR_URL | quote }}
            - name: editor.x-api-key
              value: {{ .Values.env.EDITOR_X_API_KEY | quote }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10

