apiVersion: v1
kind: Service
metadata:
  name: backend-with-cockpit
spec:
  selector:
    app: backend-with-cockpit
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080

